## Game of Life
### Practice for Week 6 Pair Problem

Play [Conway's Game of Life](https://playgameoflife.com/).
- Click the "Explanation" button at the bottom, and read through/watch the resources
- "Zoom in" using the "#" slider bar on the lower right, and slide it all the way to the right
- Set up some initial conditions, and use either the "Start" or "NEXT" button to walk through the process ...

Consider the following routines to try on your own in a "scratch" notebook. The pair problem will build on your understanding of these concepts.
- Write a function that will "plot" a random binary NumPy array (say, of size 10 x 10). This should look like a "mixed up" checkerboard.
- Write a function that executes one step of Conway's Game of Life for this array.
- If you can, try to write a loop that executes this function over and over until you reach a stopping condition.

---


### Game of Life Rules

Each cell has 8 neighbors:

⬛ ⬛ ⬛ 

⬛ 🟩 ⬛ 

⬛ ⬛ ⬛ 

- If populated cell has 0 or 1 neighbors, it will die.
- If populated cell has 2 or 3 neighbors, it will survive.
- If populated cell has 4 or more neighbors, it will die.
- If empty cell has 3 neighbors, it will become populated.

If cell position is considered (0, 0), relative references to 8 neighbors (delta_row, delta_col):

(-1, -1) (-1,  0) (-1, 1)

( 0, -1) ( 0,  0) ( 0, 1)

( 1, -1) ( 1,  0) ( 1, 1)

---


In [62]:
import numpy as np
import random
import time

def create_rand_array(n_rows, n_cols):
    # generate random array of binary values
    zero_one = [0, 1]
    binary_array = np.random.choice(zero_one, size = (n_rows, n_cols))
    return binary_array

def display_game(current_array):
    # symbols for cells
    alive_cell = '🟩'
    dead_cell = '⬜'

    # get dimensions of game array
    n_rows = current_array.shape[0]
    n_cols = current_array.shape[1]

    show_game = [] # empty array to hold visual game grid

    # iterate over cols in each row to show alive or dead cell based on value of array[r,c]
    for row in range(n_rows):    
        show_row = [] # empty array to hold current game row
        for col in range(n_cols):
            if current_array[row, col] == 1:
                show_row.append(alive_cell)
            else:
                show_row.append(dead_cell)  
        
        show_game.append(' '.join(show_row)) # join characters into string with space separator

    # display game grid - join row strings with new line & space separator
    print('', '\n '.join(show_game))

    return

def game_life_step(start_array):

    # get dimensions of game array
    n_rows = start_array.shape[0]
    n_cols = start_array.shape[1]

    # create array of zeros (dead cells) as blank template for next step of game
    new_array = np.full([n_rows, n_cols], 0)

    # if current cell considered (0, 0), relative positions of 8 neighbors =
    # ((-1, -1), (-1, 0), (-1, 1), (0, -1), (0, 1), (1, -1), (1, 0), (1, 1))

    # iterate over col in each row to create array slice of neighbors to cell in array[r,c]
    for row in range(n_rows):    

        for col in range(n_cols):

            # default values of array slice around current cell
            r_start = row - 1
            r_end = row + 2   # use 2 instead of 1 because last index value will be excluded
            c_start = col - 1
            c_end = col + 2   # use 2 instead of 1 because last index value will be excluded
            
            # if cell located on top or bottom edge of grid, adjust array slice values
            if row == 0:
                r_start = row
            elif row == n_rows - 1:
                r_end = n_rows

            # if cell located on left or right edge of grid, adjust array slice values
            if col == 0:
                c_start = col
            elif col == n_cols - 1:
                c_end = n_cols
        
            # get array slice representing neighbors and count alive neighbors
            neighbors = start_array[r_start:r_end, c_start:c_end]
            num_neighbors = np.sum(neighbors) # alive = 1, dead = 0

            # if alive cell, check neighbor count to see if it survives to next step
            if game_array[row, col] == 1:
                
                # subtract alive cell from neighbor count (don't count self as neighbor)
                num_neighbors -= 1
                
                # if 2 or 3 neighbors, cell will survive (otherwise, it dies; leave as default 0 in new array)
                if num_neighbors == 2 or num_neighbors == 3:
                    new_array[row, col] = 1
                    
            # else is dead cell, check neighbor count to see if becomes alive in next step
            else:
                if num_neighbors == 3:
                    new_array[row, col] = 1
    
    return new_array

def play_game(steps):
    print("Conway's Game of Life")
    game_array = create_rand_array(10, 10)
    print("Initial Random State")
    display_game(game_array)

    for step in range(steps):
        time.sleep(0.5) # delay to view steps more slowly
        game_array = game_life_step(game_array)
        print("\nStep", step + 1)
        display_game(game_array)

        # check to see if all cells dead (end game early)
        if np.sum(game_array) == 0:
            print("\nAll cells dead")
            break

    print("\nGame Over")


In [63]:
# show numeric values of randomly generated game array
example_array = create_rand_array(10, 10)
print(example_array)

[[0 1 1 1 1 0 0 1 1 0]
 [0 0 0 1 1 1 1 0 0 0]
 [1 1 0 0 1 1 1 1 1 0]
 [1 0 0 0 0 1 0 0 0 1]
 [1 0 1 0 1 0 1 0 1 1]
 [0 0 0 0 1 0 0 1 1 1]
 [1 0 0 1 0 0 1 0 1 0]
 [1 0 1 1 0 0 1 1 1 1]
 [0 0 1 0 1 0 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 1]]


In [64]:
# show visual display of this example game grid
display_game(example_array)

 ⬜ 🟩 🟩 🟩 🟩 ⬜ ⬜ 🟩 🟩 ⬜
 ⬜ ⬜ ⬜ 🟩 🟩 🟩 🟩 ⬜ ⬜ ⬜
 🟩 🟩 ⬜ ⬜ 🟩 🟩 🟩 🟩 🟩 ⬜
 🟩 ⬜ ⬜ ⬜ ⬜ 🟩 ⬜ ⬜ ⬜ 🟩
 🟩 ⬜ 🟩 ⬜ 🟩 ⬜ 🟩 ⬜ 🟩 🟩
 ⬜ ⬜ ⬜ ⬜ 🟩 ⬜ ⬜ 🟩 🟩 🟩
 🟩 ⬜ ⬜ 🟩 ⬜ ⬜ 🟩 ⬜ 🟩 ⬜
 🟩 ⬜ 🟩 🟩 ⬜ ⬜ 🟩 🟩 🟩 🟩
 ⬜ ⬜ 🟩 ⬜ 🟩 ⬜ 🟩 🟩 ⬜ ⬜
 🟩 🟩 🟩 🟩 🟩 🟩 🟩 🟩 🟩 🟩


In [65]:
# advance example game by one step
game_array = game_life_step(example_array)

In [66]:
# show new game grid (after one step)
display_game(game_array)

 ⬜ ⬜ 🟩 ⬜ ⬜ ⬜ 🟩 🟩 ⬜ ⬜
 🟩 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜
 🟩 🟩 ⬜ 🟩 ⬜ ⬜ ⬜ ⬜ 🟩 ⬜
 ⬜ ⬜ ⬜ 🟩 🟩 ⬜ ⬜ ⬜ ⬜ 🟩
 ⬜ 🟩 ⬜ 🟩 🟩 🟩 🟩 ⬜ ⬜ ⬜
 ⬜ 🟩 ⬜ 🟩 🟩 ⬜ 🟩 ⬜ ⬜ ⬜
 ⬜ 🟩 🟩 ⬜ 🟩 🟩 ⬜ ⬜ ⬜ ⬜
 ⬜ ⬜ ⬜ ⬜ 🟩 ⬜ ⬜ ⬜ ⬜ 🟩
 🟩 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜
 ⬜ 🟩 🟩 ⬜ 🟩 ⬜ ⬜ ⬜ 🟩 ⬜


In [61]:
# have computer play game (# steps)
play_game(20)

Conway's Game of Life
Initial Random State
 ⬜ ⬜ ⬜ 🟩 🟩 🟩 🟩 🟩 🟩 ⬜
 🟩 🟩 ⬜ ⬜ 🟩 🟩 🟩 ⬜ 🟩 🟩
 ⬜ 🟩 🟩 🟩 🟩 ⬜ ⬜ 🟩 ⬜ ⬜
 ⬜ ⬜ ⬜ ⬜ 🟩 🟩 ⬜ 🟩 🟩 ⬜
 ⬜ 🟩 🟩 🟩 🟩 🟩 ⬜ ⬜ ⬜ 🟩
 ⬜ ⬜ 🟩 ⬜ 🟩 🟩 ⬜ 🟩 🟩 🟩
 🟩 ⬜ 🟩 🟩 ⬜ 🟩 🟩 ⬜ ⬜ 🟩
 ⬜ ⬜ 🟩 ⬜ ⬜ ⬜ 🟩 ⬜ ⬜ 🟩
 ⬜ ⬜ 🟩 ⬜ ⬜ ⬜ ⬜ 🟩 ⬜ 🟩
 🟩 🟩 🟩 ⬜ 🟩 ⬜ ⬜ ⬜ 🟩 ⬜

Step 1
 ⬜ ⬜ ⬜ 🟩 ⬜ ⬜ ⬜ ⬜ ⬜ 🟩
 🟩 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ 🟩
 🟩 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ 🟩
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ 🟩 ⬜ ⬜
 ⬜ 🟩 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ 🟩 ⬜ ⬜
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜
 ⬜ ⬜ ⬜ ⬜ ⬜ 🟩 ⬜ 🟩 ⬜ 🟩
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ 🟩 🟩 🟩
 ⬜ 🟩 🟩 🟩 ⬜ ⬜ ⬜ ⬜ 🟩 ⬜

Step 2
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ 🟩 🟩
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ 🟩 ⬜
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ 🟩 ⬜ 🟩 ⬜
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ 🟩 🟩 ⬜ 🟩
 ⬜ ⬜ 🟩 ⬜ ⬜ ⬜ 🟩 🟩 ⬜ ⬜
 ⬜ ⬜ 🟩 ⬜ ⬜ ⬜ ⬜ 🟩 🟩 🟩

Step 3
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ 🟩 🟩
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ 🟩 🟩
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ 🟩 ⬜ 🟩 ⬜
 ⬜ ⬜ ⬜ ⬜ ⬜ 🟩 ⬜ ⬜ ⬜ ⬜
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ 🟩
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ 🟩 🟩 🟩 ⬜

Step 4
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ 🟩
 ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜
 